### PR TITLE
Updated Mac XCode Projects Take 2

### PR DESCRIPTION
**Pull request by KirbyKid256**
So last time I accidentally broke it by swapping the xcode projects for the Dependencies and the Engine. This time, I suffered an ungodly amount of time figuring out how to apply compiler flags and getting the autobuild to work, also after messing up my forks having to redo everything.

This pull request the RSDKv3 mac builds up to speed with the latest GitHub commit. This includes updated icons, making sure the build doesn't crash for me, and being able to easily building signed frameworks for Ogg, Vorbis, and Theora. The new README also includes how to use and modify the CXX Flags.

The majority of the code is from @Sappharad's fork, although I did get permission beforehand to use it to do a pull request. I I have edited and removed some of the changes from the fork.

Please test this on Windows before you pull because while not much should have changed, I can't test it on Windows because I don't know how to compile it for Windows while on a Mac.

As for the autobuild, if you download the `v3-mac.zip` it will say that the app is broken. That is wrong. To be able to use it, run `xattr -cr RSDKv3.app` assuming your current directory is where the app is. Or just type `xattr -cr ` and drop the app into the Terminal.

### CODE REVIEW

**Comment by KirbyKid256** [comment]
Was tired and hungry last night so I forgot to mention this resolves #221

**Comment by KirbyKid256** [comment]
Hold on a sec the fullscreen doesn't look right
Screenshot 2024-09-06 at 8 18 29 AM

**Comment by KirbyKid256** [comment]
Hold up I do need to check if mods are funky. And also I'm gonna change the location of where the frameworks build so it's easier

**Comment by Mefiresu** [comment]
> As for the autobuild, if you download the `v3-mac.zip` it will say that the app is broken. That is wrong. To be able to use it, run `xattr -cr RSDKv3.app` assuming your current directory is where the app is. Or just type `xattr -cr ` and drop the app into the Terminal.

Google says it's because the app hasn't been signed.
As code signing can be a bit difficult to set up correctly, can running `xattr -cr RSDKv3.app` after the building step fix the issue?

**Comment by KirbyKid256** [comment]
> Google says it's because the app hasn't been signed. As code signing can be a bit difficult to set up correctly, can running `xattr -cr RSDKv3.app` after the building step fix the issue?

Well if you build it yourself then there's no need to use that command. And if you were to upload it to for example Google Drive and redownload it, all you will need to do is hold Ctrl, click the app, and select open to allow the option to open anyways. However, for some reason if you download it via the GitHub actions autobuild, you need to use the `xattr -cr` command on the downloaded zip or app itself in order to open it, otherwise it will say it's damaged. I could try to see if I can apply the command through the autobuild after it zipped to see if it sticks but otherwise you'll have to do the command yourself.

**Comment by KirbyKid256** [comment]
Nope, I don't think it does

**Comment by Sappharad** [comment]
The xattr command is just telling your local machine to trust the unsigned app. It won’t affect any other machines. 

The only solution that doesn’t require workarounds is actual code signing, but I don’t think you’re going to find a developer who wants to put their paid signing keys on a public GitHub build.

The right-click open trick is also being removed in macOS 15 that comes out next week. The only options for working builds would be getting a dev to sign them for you, building it yourself because it signs for the machine you build on, or the getting an unsigned build and running the xattr command to set the trusted attribute.

**Comment by Mefiresu** [comment]
> The only solution that doesn’t require workarounds is actual code signing, but I don’t think you’re going to find a developer who wants to put their paid signing keys on a public GitHub build bot.

I was wondering we could use self signed certificates for this as well, which imo would be good enough for such a project. Do you know if this is possible on macOS?

**Comment by KirbyKid256** [comment]
... Are you serious?

**Pull request closed without merging**
